### ISSUE TITLE
Investigate MYC issue with start and end date

### ISSUE THREAD

**Issue by grange85** [nationalarchives/manage-your-collections#1]
ASD have logged a called from Nottingham University who have used the MYC and entered start and end dates for a record. However, this data has not been added to Discovery or search and so are treated as dates unknown. Covering dates are OK.

Gnanesh suggests that the problem is with the mapper. (I have wider concerns about the business rules for dates - but that is a different issue and one I wish I had known about earlier)

See for example: 
Link to search results page (1st result)
https://discovery.nationalarchives.gov.uk/results/r?_q=Bloodaxe+Books+archive 

Link to catalogue description
http://discovery.nationalarchives.gov.uk/details/r/549a015c-062c-4525-9b62-6d183e1e1cc2

**Comment by carol-df** [comment]
I found a bug in the excel reader, when it's reading in a spreadsheet with all three dates columns: covering_dates, start_date and end_date, the covering_dates field is read in and the start and end dates are skipped and not loaded. NB. It's fine for a spreadsheet that just has start and end dates, they are read in fine. I've fixed the bug and put it on test. 
There is also a problem with the test external client that users use for testing which is being investigated.
I've created spreadsheet that has all the details of the effected loads and sent it to Jo Pugh and Caroline Catchpole. And retrieved all the identified spreadsheets. Some of the loads were only 1 record and the correction of those records can be done in MYC using the 'Edit Discovery Record' procedure and could be done now. For the larger loads, it's probably safest to download the effected collections paste in the start and end dates and reload or just reload the effected spreadsheets. This will need to wait until the fix has gone live.
So currently awaiting  resolving the test myc external client website not available issue.

**Comment by carol-df** [comment]
The test system issue has been resolved.
The bug has been fixed and tested, deployed and tested on test by the myc team and deployed to live.
I've provided the myc team with the data and spreadsheets for any collections that require reloading.
