### ISSUE TITLE
Priority: 4 - MYC Performance issues when multiple users on system

### ISSUE THREAD

**Issue by mentionthewar** [nationalarchives/manage-your-collections#10]
On Friday 15th March we ran a workshop introducing the system to new users. There were about 25 attendees. Some but by no means all experimented with uploading data. The system was handling more jobs than normal and it didn't perform all that well - jobs using the template seemed to complete normally but mapper jobs stalled - neither obviously failing, nor completing after perhaps 20 minutes. (I have no reason to believe the data volumes involved were large). We don't have an easy way of simulating increased traffic to the system but as the number of active users rises load testing of some kind would be very beneficial.

**Comment by mcieslak** [comment]
**Priority score: 4** (prioritised with Jo 22/03/19)

- Benefit to user - 1
- Benefit to TNA - 1
- Impact of doing nothing - 2

In addition to the performance issues , the system fails silently - **No user or system feedback**.  Jo expected the system to work in batches in order to avoid this stalling of data uploading.

**Comment by CarolD** [comment]
I'm wondering if this was on Friday 15th or Thursday 14th? looking at what was happening on the system it looked more like it could have been the 14th to me. I'm going to have a look at what I can glean was going on with the system on that day to better understand the issue

**Comment by CarolD** [comment]
**Analysis of MYC workshop 14/03/2019**
Analysis is based primarily on the MYC application log (MYC Database ActionLog collection) and the Logging database MYC table.
Id	Count	Action with final stage
1	9	Successful deletes
2	7	Successful TSV Exports
3	10	Successful updates
4	35	Successful Excel imports – all the way through
5	13	Excel Imports that failed data validation
6	12	Excel Imports ended in a ‘system’ error (some same workload put through several times)
7	7	Excel Imports at ‘awaiting mapping’ stage
8	6	Excel Imports rejected at preview stage
9	5	Excel Imports ‘stuck’ after virus scanned stage

**Stuck on upload after virus scan**
This isn't unique to mapped files as this processing is exactly the same for default and mapped files. 
There were 5 instances that only occurred on this one afternoon between 15:14 and 15:44
As background on the architecture, the processing occurs over 2 load balanced servers. These servers are used by all the other Discovery services and other services like doris. In MYC, we use a messaging system between the api and the lower level operations like interactions with the databases and data files by the a2a service and log operations by the action logs service. Messages get posted to the queue and then picked up by the service in First In First Out order by worker threads and acted upon.
At 15:14 and 15:24 this happened on server 2 and at 15:25 and 15:37 this happened on server 1, then there was one more instance at 15:44 on server 2. 
Looking at what happens in the code, all up to putting a message in the queue appears to have happened but I can’t see any evidence that anything has been done on the processing of the message at the other side.
What I’d like to do, is just before the message is queued write to the log that it’s been queued and the time and then as soon as an import excel message is picked up by the service is to write to the log that its starting processing and the time. To see if messages are being picked up when it’s busy and if there are time gaps when it’s busy. There are other messages that appear to be processed at this time.
For the testing, I’m proposing a console app that’s going to fire off import messages, configurable for the number of messages, different sized files etc. to load the system with imports.

**System errors**
When there is an unsuccessful state that is not currently handled, it is bucketed into ' there has been a system failure, please try again'
Id	Count	detail	note
1	3	Trying to upload an encrypted file 3 times	
2	2	Worksheet position out of range	Worth trying to replicate and see what’s causing it
3	2	Key not present in the dictionary	Worth trying to replicate and see what’s causing it
4	4	Failed to GetMappingByArchiveId	Worth trying to replicate and see what’s causing it
5	1	Value cannot be null Parameter name: address	Worth trying to replicate and see what’s causing it

At other time have also seen bulk write operations resulting in 1 or more errors – waiting for replication. Which may be the kind of thing that’s behind ‘stuck’ in publication.
It could be worth opening a separate issue to take a look at ‘system’ errors, to see if any could be resolved. I don't think they are performance related.

**Comment by CarolD** [comment]
I've done load testing, uploading the kenrick collection spreadsheet which is a reasonable size, against just 1 server, 10 requests and 20 requests ( this is equivalent to 20 and 40 requests coming in as they get dished out between 2 servers so each server gets half the requests) The performance was fine, i'll send jo the results. So standalone the system seems very capable of dealing with load. The only thing is in production the servers are also serving all the other Discovery services. It may be worth running the 20 test on a production server at midday. The other thing is loads appearing as stuck can also be the result of some kind of error that's not to do with performance. I inadvertently reproduced this be putting an invalid filename in a log record.

**Comment by CarolD** [comment]
CC flagged up a similar issue on 17/05/2019
a export job and collection update job were queued then nothing else happened also the users email was missing to email the validation report, Value cannot be null Parameter name: address as occured above.
The user was the only one using myc at the time, so doesn't appear to be performance, no one else had any problems that day, no errors.

**Comment by CarolD** [comment]
Monday 17/06 I did a load test on production 4pm that worked fine
18/06 workshop that expecienced the same issues as last workshop.
I did notice that one export job ran from 1:30 to 5:30 ie. taking 4 hrs (long time).
We've recently seen memory issues effecting Discovery Services ( on same servers as MYC).
The memory on these servers is small and is probably why the exports take such a long time.
IT are looking and hopefully will increase the memory on the servers, this should improve MYC performance generally.

**Comment by julieguthrie** [comment]
@ACTNA did the recent fix to the 'system error' message get deployed in the last 3 weeks?

**Comment by julieguthrie** [comment]
@mentionthewar to check once Andrew confirms & close if this is resolved.

**Comment by Puththiran** [comment]
[17-06-2020 Maria]
Jo will close this issue as the simple report they receive just needs to be refined a little - no user impact

**Comment by mentionthewar** [comment]
Andrew confirms that live matches test, so changes to messaging has been published and more provision is now in place to prevent memory leaks. So this would seem to have been tackled from all fronts.
