### ISSUE TITLE
Priority:7 - MYC - No link to return to MYC from pages in Discovery

### ISSUE THREAD

**Issue by mentionthewar** [nationalarchives/manage-your-collections#5]
Links from MYC -> Discovery are a one way trip.
This allows users to become ‘marooned’ in their own content.

**Comment by mcieslak** [comment]
**Priority score: 7** (prioritised with Jo 22/03/19)

Benefit to user - 3
Benefit to TNA - 2
Impact of doing nothing - 2

UI change to allow users to return to MYC from DISCOVERY

**Comment by Puththiran** [comment]
Can include a link to go back to MYC, but where you want the link?
1. In the drop-down list 
2. Next to edit, delete links? 

![disc](https://user-images.githubusercontent.com/40386980/69717259-a213c480-1103-11ea-9814-942c620e1a66.PNG)

**Comment by julieguthrie** [comment]
@Puththiran estimates small effort for this

**Comment by Puththiran** [comment]
[17-06-2020 Maria]
Matt Blair to confirm whether a front end solution was developed for this during the project development phase but never implemented.

**Comment by mentionthewar** [comment]
UI adjusted and live.
