### ISSUE TITLE
Priority: 7 - MYC Users cannot export all their data easily

### ISSUE THREAD

**Issue by mentionthewar** [nationalarchives/manage-your-collections#7]
We often preach about easy data extraction but MYC does not provide 1-click data download of all fonds.

**Comment by mcieslak** [comment]
**Priority score: 7** (prioritised with Jo 22/03/19)

Benefit to user - 2
Benefit to TNA - 2
Impact of doing nothing - 3

TNA reputation at risk as this is bad practice. There is a workaround by using filters but a single download ALL FONDS button is required for users.

**Comment by Puththiran** [comment]
This is currently impossible with the in house set-up with shared resources, even if its a cloud based it will be very costly, we are trying to retrieve bulk data from a live db which is used by several other applications (Discovery, etc.)
There may be a potential requirement followed by "upload all the fonds in one go"

**Comment by Puththiran** [comment]
[17-06-2020 Maria]
This is a request to enable bulk export of data - Gnanesh has commented that this request is IMPOSSIBLE.
Perhaps Jo to speak to Gnanesh and then close or refine issue.

**Comment by Puththiran** [comment]
[19-06-2020 Jo]
What I envisaged here was a job that processed overnight, chugged through the (say) 5000 fonds and produced a zip of all the spreadsheets/tsv-s for subsequent download. (perhaps held on the server only for a limited time, though I can’t imagine the file could actually be so very large).

It seems to me that this should be workable though I accept it may be a larger piece of work than the other issues and you might well grade it accordingly. I can’t say that it seems on the face of it impossible. What am I missing?

**Comment by Puththiran** [comment]
All the user request will be queued and performed one by one
The scheduled task will run the job only at the Discovery identified low utilization period
The download data moved to S3 for users to download.
The files won't be break into small pieces regardless of its size
The export is only based Excel

**Comment by Puththiran** [comment]
I've changed the current export function to support archive level export with the following limitations
- It won't work for the larger archive collection
- even for smaller archive it may run for couple of days to prepare the file
- only allowed for staff to run this export, on behalf of the external request


![image](https://user-images.githubusercontent.com/40386980/86906563-a4afb100-c10b-11ea-8ed5-82ee21cb3348.png)

**Comment by mentionthewar** [comment]
Export using internal tool, for provision to external users, now tested and live. Great work.
