### ISSUE TITLE
Priority: 3 Tracking metadata published to Discovery not adequate to measure MYC use

### ISSUE THREAD

**Issue by mentionthewar** [nationalarchives/manage-your-collections#8]
Helen Oake reports that new descriptions published to Discovery through MYC have header metadata identical in every respect to old A2A files. This means we can't measure traffic separately between the two datasets.

If the relevant field was populated differently at publication, better metrics would be possible. The culprit would seem to be:

<meta name="DCSext.colltype" content="A2A">

**Comment by mcieslak** [comment]
**Priority score: 3** (prioritised with Jo 22/03/19)

Benefit to user - 1
Benefit to TNA - 1
Impact of doing nothing - 1

Helen Oake to identify specific metadata for MYC and Carol D to implement?

**Comment by hoake** [comment]
We've done a mini explore if MYC specific usage can be tracked. Unfortunately MYC updates to the A2A dataset and cannot be separated. We CAN track usage through A2A, NRA and Archon datasets and the metadata for this is already in place. We need to further develop our tracking scripts to pick these up and send them to GA. Ideally this would be a task for James and peer reviewed by either Mihai or Punal.

**Comment by hoake** [comment]
See issue
https://github.com/nationalarchives/tna-google-tag-manager-scripts/issues/53

**Comment by Puththiran** [comment]
[17-06-2020 Maria]
Jo will close this issue as the simple report they receive just needs to be refined a little - no user impact

**Comment by Puththiran** [comment]
[19-06-2020 Jo]
I do have one question on this. I don’t think we need additional tracking and we’re getting on well with the email reports you devised. But would it be possible for those reports to make clear whether uploads are first time uploads or reuploads? It seems to me that the system knows this (it checks, after all, to see if fond level codes duplicate). Could that status be reflected in the email report?

**Comment by Puththiran** [comment]
Have to introduce a new flag to indicate first time upload and re-upload, can be done estimated effort is Medium.

**Comment by mentionthewar** [comment]
Email report tweaked to distinguish between edit and uploads. Now live.
